package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var generateHooksCmd = &cobra.Command{
	Use:   "generate-hooks",
	Short: "Generate Git hooks for Envault",
	Long: `Generate Git hooks for Envault to automatically pull environment variables after updating code workspace.
This command creates a post-merge hook in your local .git/hooks directory that safely runs 'envault pull'.`,
	Run: func(cmd *cobra.Command, args []string) {
		// Check if .git directory exists
		if _, err := os.Stat(".git"); os.IsNotExist(err) {
			fmt.Println("Error: .git directory not found. Please run this command at the root of a Git repository.")
			os.Exit(1)
		}

		hooksDir := filepath.Join(".git", "hooks")
		if _, err := os.Stat(hooksDir); os.IsNotExist(err) {
			if err := os.Mkdir(hooksDir, 0755); err != nil {
				fmt.Printf("Error creating hooks directory: %v\n", err)
				os.Exit(1)
			}
		}

		postMergePath := filepath.Join(hooksDir, "post-merge")
		hookContent := `#!/bin/sh
# Generated by Envault
if command -v envault >/dev/null 2>&1; then
    envault pull
fi
`

		// Check if it already exists, if so append or warn? We can just append if it exists, or overwrite. Let's overwrite / create.
		if _, err := os.Stat(postMergePath); err == nil {
			fmt.Println("Existing post-merge hook found. Appending envault pull to it...")
			f, err := os.OpenFile(postMergePath, os.O_APPEND|os.O_WRONLY, 0755)
			if err != nil {
				fmt.Printf("Error opening post-merge hook: %v\n", err)
				os.Exit(1)
			}
			defer f.Close()
			if _, err := f.WriteString("\n" + hookContent); err != nil {
				fmt.Printf("Error writing to post-merge hook: %v\n", err)
				os.Exit(1)
			}
			f.Chmod(0755)
		} else {
			if err := os.WriteFile(postMergePath, []byte(hookContent), 0755); err != nil {
				fmt.Printf("Error creating post-merge hook: %v\n", err)
				os.Exit(1)
			}
		}

		fmt.Println("Successfully generated post-merge hook.")
	},
}

func init() {
	rootCmd.AddCommand(generateHooksCmd)
}
